name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # lub master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_SERVICE_ID: ${{ secrets.VITE_SERVICE_ID }}
      VITE_TEMPLATE_ID_OWNER: ${{ secrets.VITE_TEMPLATE_ID_OWNER }}
      VITE_TEMPLATE_ID_CLIENT: ${{ secrets.VITE_TEMPLATE_ID_CLIENT }}
      VITE_PUBLIC_KEY: ${{ secrets.VITE_PUBLIC_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
